[project]
name = "nd-super-nodes"
description = "Super LoRA Loader and ND Super Selector overlays for ComfyUI."
version = "1.8.1"
license = {file = "LICENSE"}
dependencies = [
	"aiohttp>=3.8.0"
]

[project.urls]
Repository = "https://github.com/Afrody9387/nd-super-nodes"
#  Used by Comfy Registry https://registry.comfy.org

[tool.comfy]
DisplayName = "ND Super Nodes (Afrody fork)"
Icon = "https://raw.githubusercontent.com/Afrody9387/nd-super-nodes/refs/heads/main/icon.png"
includes = []
